sudo: false
language: node_js
branches:
  only:
  - master
  - develop
cache: yarn
stages:
- name: lint
  if: branch = develop OR branch = master
- name: compile
  if: branch = develop OR branch = master
- name: test
  if: branch = develop OR branch = master
- name: deploy
  if: branch = master AND type = push
jobs:
  include:
  - stage: lint
    script: yarn run lint
    node_js:
    - '11'
  - stage: compile
    script: yarn build
    node_js:
    - '11'
  - stage: test
    script: yarn test:ci
    node_js:
    - '10'
    - '11'
  - stage: deploy
    script:
    - yarn install
    - yarn build
    - echo "//registry.npmjs.org/:_authToken='${NPM_TOKEN}'" >> .npmrc
    - npm publish
    - cp .npmrc.template .npmrc
    node_js:
    - '11'
