sudo: false
language: node_js
branches:
  only:
  - develop
cache: yarn
stages:
- name: lint
  if: branch = develop
- name: compile
  if: branch = develop
- name: test
  if: branch = develop
- name: deploy
  if: branch = master AND type = push
jobs:
  include:
  - stage: lint
    script: yarn run lint
    node_js:
    - '10'
  - stage: compile
    script: yarn build
    node_js:
    - '10'
  - stage: test
    script: yarn test
    node_js:
    - '10'
    - '11'
  - stage: deploy
    script:
    - yarn install
    - yarn build
    - echo '//registry.npmjs.org/:_authToken="${NPM_TOKEN}"' >> .npmrc
    - npm publish
    - cp .npmrc.template .npmrc
    node_js:
    - '10'
    - '11'
